INSERT INTO customers (id, name, email, tier, created_at) VALUES
    ('11111111-1111-1111-1111-111111111111', 'Acme Industrial', 'support@acme.example', 'enterprise', NOW() - INTERVAL '180 days'),
    ('22222222-2222-2222-2222-222222222222', 'Bluebird Retail', 'ops@bluebird.example', 'business', NOW() - INTERVAL '120 days'),
    ('33333333-3333-3333-3333-333333333333', 'Northwind Labs', 'hello@northwind.example', 'starter', NOW() - INTERVAL '45 days');

INSERT INTO cases (
    id,
    subject,
    description,
    status,
    priority,
    category,
    customer_id,
    assigned_agent_id,
    ai_summary,
    ai_suggested_action,
    sentiment_score,
    created_at,
    updated_at,
    resolved_at,
    sla_deadline,
    sla_breached
) VALUES
    (
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1',
        'Damaged monitor arrived',
        'Customer received a cracked monitor and attached photos of the damaged packaging.',
        'new',
        'high',
        'shipping_damage',
        '11111111-1111-1111-1111-111111111111',
        '44444444-4444-4444-4444-444444444441',
        'Customer reported transit damage to a replacement monitor and expects a fast resolution.',
        'Offer an expedited replacement and create a carrier damage claim.',
        -0.72,
        NOW() - INTERVAL '6 hours',
        NOW() - INTERVAL '2 hours',
        NULL,
        NOW() + INTERVAL '18 hours',
        FALSE
    ),
    (
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2',
        'Invoice shows duplicate charge',
        'Billing team from Bluebird Retail says their April invoice includes the same service fee twice.',
        'open',
        'medium',
        'billing',
        '22222222-2222-2222-2222-222222222222',
        '44444444-4444-4444-4444-444444444442',
        'Likely duplicate billing line item affecting a business customer renewal invoice.',
        'Review invoice history and issue a credit memo if duplication is confirmed.',
        -0.28,
        NOW() - INTERVAL '2 days',
        NOW() - INTERVAL '3 hours',
        NULL,
        NOW() + INTERVAL '1 day',
        FALSE
    ),
    (
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3',
        'Cannot reset admin password',
        'Northwind Labs reports that password reset emails never arrive for the workspace admin account.',
        'pending_customer',
        'medium',
        'authentication',
        '33333333-3333-3333-3333-333333333333',
        '44444444-4444-4444-4444-444444444443',
        'Password reset workflow may be blocked by an email filter or misconfigured sender domain.',
        'Confirm spam filtering rules and resend a reset link from the admin console.',
        -0.14,
        NOW() - INTERVAL '1 day',
        NOW() - INTERVAL '6 hours',
        NULL,
        NOW() + INTERVAL '2 days',
        FALSE
    ),
    (
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4',
        'Need return label for unopened accessories',
        'Customer wants to return unopened keyboard accessories within the standard return window.',
        'resolved',
        'low',
        'returns',
        '22222222-2222-2222-2222-222222222222',
        '44444444-4444-4444-4444-444444444444',
        'Straightforward return request within policy window.',
        'Send a prepaid return label and refund after warehouse receipt.',
        0.11,
        NOW() - INTERVAL '10 days',
        NOW() - INTERVAL '8 days',
        NOW() - INTERVAL '8 days',
        NOW() - INTERVAL '9 days',
        FALSE
    ),
    (
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5',
        'Order tracking has not updated for replacement part',
        'Enterprise customer says the replacement part has been in preparing state for four days with no carrier scan.',
        'escalated',
        'urgent',
        'order_tracking',
        '11111111-1111-1111-1111-111111111111',
        '44444444-4444-4444-4444-444444444445',
        'Shipment may be stalled before handoff to the carrier and is at risk of breaching the enterprise SLA.',
        'Escalate to fulfillment operations and provide a proactive status update to the customer.',
        -0.61,
        NOW() - INTERVAL '3 days',
        NOW() - INTERVAL '30 minutes',
        NULL,
        NOW() - INTERVAL '1 hour',
        TRUE
    );

INSERT INTO case_comments (id, case_id, author, content, is_internal, created_at) VALUES
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb001', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1', 'Casey Agent', 'I reviewed the photos and the carton damage is consistent with transit impact.', TRUE, NOW() - INTERVAL '4 hours'),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb002', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1', 'Acme Industrial', 'Please replace the unit before Friday if possible.', FALSE, NOW() - INTERVAL '3 hours'),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb003', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2', 'Morgan Finance', 'We are comparing the invoice against the signed renewal order now.', TRUE, NOW() - INTERVAL '5 hours'),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb004', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3', 'Northwind Labs', 'We checked spam and quarantine folders but did not find the email.', FALSE, NOW() - INTERVAL '8 hours'),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbb005', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5', 'Avery Escalations', 'Warehouse escalation opened with fulfillment ticket WH-2048.', TRUE, NOW() - INTERVAL '20 minutes');

INSERT INTO knowledge_base_articles (id, title, content, category, tags, helpful_count, created_at, updated_at) VALUES
    ('cccccccc-cccc-cccc-cccc-ccccccccc001', 'How to report shipping damage', 'Inspect the package, photograph the damage, and open a support case with order details within 48 hours of delivery.', 'shipping_damage', 'shipping,damage,claims', 24, NOW() - INTERVAL '90 days', NOW() - INTERVAL '15 days'),
    ('cccccccc-cccc-cccc-cccc-ccccccccc002', 'Understanding billing adjustments', 'Billing adjustments appear as separate line items. Review your invoice summary and contact support if you see duplicate charges.', 'billing', 'billing,invoices,credits', 18, NOW() - INTERVAL '85 days', NOW() - INTERVAL '10 days'),
    ('cccccccc-cccc-cccc-cccc-ccccccccc003', 'Resetting your account password', 'Use the forgot password link, allow up to ten minutes for email delivery, and add our sender domain to your safe list.', 'authentication', 'password,login,security', 31, NOW() - INTERVAL '70 days', NOW() - INTERVAL '6 days'),
    ('cccccccc-cccc-cccc-cccc-ccccccccc004', 'Returning eligible products', 'Unopened products can be returned within 30 days. Request a label from the support portal and keep the tracking receipt.', 'returns', 'returns,refunds,labels', 16, NOW() - INTERVAL '65 days', NOW() - INTERVAL '3 days'),
    ('cccccccc-cccc-cccc-cccc-ccccccccc005', 'Checking order tracking status', 'Tracking updates can take up to 24 hours after shipment creation. If there is no scan after two business days, contact support.', 'order_tracking', 'orders,tracking,shipping', 22, NOW() - INTERVAL '60 days', NOW() - INTERVAL '1 day');
